package com.neostencil.model.entities;

public enum AuthorityName {
  ROLE_STUDENT, ROLE_ADMIN, ROLE_INSTRUCTOR, ROLE_WRITER, ROLE_USER, ROLE_SALES, ROLE_EDITOR,ROLE_TECHOPS,ROLE_LMS_ADMIN, ROLE_SPECIAL_ACCESS,ROLE_APPROVER,ROLE_PARENT;
}
